Update recovery.yml

diff --git a/.github/workflows/recovery.yml b/.github/workflows/recovery.yml
--- a/.github/workflows/recovery.yml
+++ b/.github/workflows/recovery.yml
@@ -17,7 +17,7 @@ jobs:
 
     steps:
     - name: Check Out
-      uses: actions/checkout@main
+      uses: actions/checkout@v2
 
     - name: Prepare the environment
       run: |
@@ -25,27 +25,29 @@ jobs:
 
     - name: Fetch image from URL
       run: |
-        echo "Downloading recovery image from: ${{ github.event.inputs.RECOVERY_URL }}"
-        wget "${{ github.event.inputs.RECOVERY_URL }}" -O recovery.img
+        wget --no-check-certificate ${{ github.event.inputs.RECOVERY_URL }} -O recovery.img
+        ls -l  # Verificar si el archivo se descargó
 
     - name: Patch Process-1
       run: |
-        chmod a+x script1.sh
-        chmod a+x magiskboot
+        chmod a+x script1.sh magiskboot
         ./script1.sh || true
 
     - name: Patch Process-2
       run: |
         chmod a+x script2.sh
-        ./script2.sh || true
+        ./script2.sh
+        if [ ! -f "recovery-patched.img" ]; then
+          echo "Error: recovery-patched.img not found"
+          exit 1
+        fi
         python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
-        python3 avbtool add_hash_footer --partition_name recovery --partition_size $(wc -c recovery.img |cut -f 1 -d ' ') --image recovery-patched.img --key phh.pem --algorithm SHA256_RSA4096
-        mkdir output && cd output
-        mv ../recovery-patched.img recovery.img
-        tar cvf fastbootd-recovery.tar recovery.img
+        python3 avbtool add_hash_footer --partition_name recovery --partition_size $(wc -c recovery.img | cut -f 1 -d ' ') --image recovery-patched.img --key phh.pem --algorithm SHA256_RSA4096
+        mkdir output && mv recovery-patched.img output/recovery.img
+        tar cvf output/fastbootd-recovery.tar output/recovery.img
 
     - name: Upload Recovery
       uses: actions/upload-artifact@v3.0.0
       with:
-        path: /home/runner/work/Patch-Recovery/Patch-Recovery/output/*.tar
+        path: output/*.tar
         name: Patched-Recovery
