Update recovery.yml

diff --git a/.github/workflows/recovery.yml b/.github/workflows/recovery.yml
--- a/.github/workflows/recovery.yml
+++ b/.github/workflows/recovery.yml
@@ -8,6 +8,9 @@ on:
         required: true
         default: 'https://we.tl/t-MKbgvT5uQT'
 
+env:
+  RECOVERY_URL: https://we.tl/t-MKbgvT5uQT
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -23,37 +26,48 @@ jobs:
     - name: Fetch image from URL
       run: |
         wget ${{ github.event.inputs.RECOVERY_URL }}
-        ls
-        pwd
-
+        ls -lh  # Comprobamos si el archivo se ha descargado correctamente
+    
     - name: Verify Downloaded File
       run: |
-        ls -lh
-        file $(basename ${{ github.event.inputs.RECOVERY_URL }})
+        FILE=$(basename ${{ github.event.inputs.RECOVERY_URL }})
+        if [ ! -f "$FILE" ]; then
+          echo "Downloaded file not found!"
+          exit 1
+        fi
+        file $FILE  # Muestra el tipo de archivo descargado
+        mv $FILE recovery.img  # Renombrar si es necesario
 
     - name: Patch Process-1
       run: |
         chmod a+x script1.sh
         chmod a+x magiskboot
         ./script1.sh || true
-        
+
     - name: Patch Process-2
       run: |
         chmod a+x script2.sh
         ./script2.sh || true
-        
-    
-    
-    - name: Continue with AVB Tool Processing
-      run: |
         python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
-        python3 avbtool add_hash_footer --partition_name recovery --partition_size $(wc -c recovery.img | cut -f 1 -d ' ') --image recovery-patched.img --key phh.pem --algorithm SHA256_RSA4096
+        
+        # Verificación de la existencia del archivo parcheado
+        if [ ! -f recovery-patched.img ]; then
+          echo "recovery-patched.img not found!"
+          exit 1
+        fi
+        
+        # Agregar hash_footer y procesar el archivo parcheado
+        python3 avbtool add_hash_footer --partition_name recovery --partition_size $(wc -c recovery-patched.img | cut -f 1 -d ' ') --image recovery-patched.img --key phh.pem --algorithm SHA256_RSA4096
+
+        # Crear carpeta de salida y empaquetar los archivos generados
         mkdir output && cd output
         mv ../recovery-patched.img recovery.img
         tar cvf fastbootd-recovery.tar recovery.img
-        
+        md5sum -t fastbootd-recovery.tar >> fastbootd-recovery.tar
+        mv fastbootd-recovery.tar fastbootd-recovery.tar.md5
+    
     - name: Upload Recovery
       uses: actions/upload-artifact@v3
       with:
-        path: /home/runner/work/Patch-Recovery/Patch-Recovery/output/*.tar
+        path: /home/runner/work/Patch-Recovery/Patch-Recovery/output/*.md5
         name: Patched-Recovery
