Update recovery.yml

diff --git a/.github/workflows/recovery.yml b/.github/workflows/recovery.yml
--- a/.github/workflows/recovery.yml
+++ b/.github/workflows/recovery.yml
@@ -6,7 +6,7 @@ on:
       RECOVERY_URL:
         description: 'RECOVERY URL'
         required: true
-        default: 'https://we.tl/t-MKbgvT5uQT'  # This will be your default link
+        default: 'https://we.tl/t-MKbgvT5uQT'
 
 jobs:
   build:
@@ -19,7 +19,7 @@ jobs:
     - name: Prepare the environment
       run: |
         sudo apt install git wget lz4 tar openssl python3 -y
-        
+
     - name: Fetch image from URL
       run: |
         wget ${{ github.event.inputs.RECOVERY_URL }}
@@ -30,7 +30,7 @@ jobs:
       run: |
         ls -lh
         file $(basename ${{ github.event.inputs.RECOVERY_URL }})
-        
+
     - name: Patch Process-1
       run: |
         chmod a+x script1.sh
@@ -41,8 +41,18 @@ jobs:
       run: |
         chmod a+x script2.sh
         ./script2.sh || true
+
+    - name: Verify new-boot.img exists  
+      run: |
+        if [ ! -f new-boot.img ]; then
+          echo "new-boot.img not found!"
+          exit 1
+        fi
+        
+    - name: Continue with AVB Tool Processing
+      run: |
         python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
-        python3 avbtool add_hash_footer --partition_name recovery --partition_size $(wc -c recovery.img |cut -f 1 -d ' ') --image recovery-patched.img --key phh.pem --algorithm SHA256_RSA4096
+        python3 avbtool add_hash_footer --partition_name recovery --partition_size $(wc -c recovery.img | cut -f 1 -d ' ') --image recovery-patched.img --key phh.pem --algorithm SHA256_RSA4096
         mkdir output && cd output
         mv ../recovery-patched.img recovery.img
         tar cvf fastbootd-recovery.tar recovery.img
